# This is a basic workflow to help you get started with Actions

name: Debug git commit via SSH

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone this repository
        uses: actions/checkout@v3

      - name: Setup tmate session
        env:
          GOPATH: ${{ github.workspace }}
          THE_EVENT_NAME: ${{ github.event_name }}
          THE_EVENT_PATH: ${{ github.event_path }}
          THE_EVENT_BEFORE: ${{ github.event.before }}
          THE_EVENT_AFTER: ${{ github.event.after }}
        uses: mxschmitt/action-tmate@v3
