# This is a basic workflow to help you get started with Actions

name: Debug SMTP via SSH

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone this repository
        uses: actions/checkout@v3

      - name: Install Haraka
        run: npm install -g Haraka

      - name: Initialize Haraka configuration
        run: |
          haraka -i ${{ github.workspace }}/haraka

          # enable debug logging
          echo DEBUG > ${{ github.workspace }}/haraka/config/loglevel
          
          # add hosts to host list
          echo "example.com" >> ${{ github.workspace }}/haraka/config/host_list

          # configure haraka to only listen on the loopback interface
          sed -i 's/;listen=\[::0\]:25/listen=127.1.2.3:2525/' ${{ github.workspace }}/haraka/config/smtp.ini

          # configure plugins
          ## dnsbl
          # do not block mail from bad hosts
          sed -i 's/dnsbl/# dnsbl/' ${{ github.workspace }}/haraka/config/plugins

          ## mail_from.is_resolvable
          # allow any address
          sed -i 's/mail_from.is_resolvable/# mail_from.is_resolvable/' ${{ github.workspace }}/haraka/config/plugins

          # ## rcpt_to.in_host_list
          # # allow any address
          # sed -i 's/rcpt_to.in_host_list/# rcpt_to.in_host_list/' ${{ github.workspace }}/haraka/config/plugins

          ## queue/smtp_forward
          # do not forward mail
          sed -i 's/queue\/smtp_forward/# queue\/smtp_forward/' ${{ github.workspace }}/haraka/config/plugins

          # ## queue/quarantine
          # # quarantine mail
          # sed -i 's/# queue\/smtp_forward/queue\/quarantine/' ${{ github.workspace }}/haraka/config/plugins

          ## queue/test
          # save to tmp directory
          sed -i 's/# queue\/smtp_forward/queue\/test/' ${{ github.workspace }}/haraka/config/plugins

          # configure systemd service
          cat <<SVC > haraka.service
          #
          # systemd service file for Haraka
          #
          # Ensure that `daemonize` in `smtp.ini` is set to `false` (which is the default value).
          #
          # Put this file in /etc/systemd/system,  modify the paths to suit, then run:
          # sudo systemctl enable haraka
          # sudo systemctl start haraka
          #

          [Unit]
          Description=Haraka MTA
          After=syslog.target network.target remote-fs.target nss-lookup.target

          [Service]
          Type=simple
          PIDFile=/var/run/haraka.pid
          ExecStart=/usr/local/bin/haraka -c ${{ github.workspace }}/haraka
          KillMode=process
          PrivateTmp=true

          [Install]
          WantedBy=multi-user.target
          
          SVC
          sudo mv haraka.service /etc/systemd/system/haraka.service

      - name: Install swaks
        run: |
          sudo apt-get update
          sudo apt-get install -y swaks

          #swaks --to rx@example.com --from tx@example.com --server 127.1.2.3 --port 2525 --auth-user <username> --auth-password <password> --tls

      - name: Setup tmate session
        env:
          THE_EVENT_NAME: ${{ github.event_name }}
          THE_EVENT_PATH: ${{ github.event_path }}
          THE_EVENT_BEFORE: ${{ github.event.before }}
          THE_EVENT_AFTER: ${{ github.event.after }}
        uses: mxschmitt/action-tmate@v3
