# This is a basic workflow to help you get started with Actions

name: Debug SMTP via SSH

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone this repository
        uses: actions/checkout@v3

      - name: Install Haraka
        run: npm install -g Haraka

      - name: Initialize Haraka configuration
        run: |
          haraka -i ${{ github.workspace }}/haraka

          # enable debug logging
          echo DEBUG > ${{ github.workspace }}/haraka/config/loglevel
          
          # add hosts to host list
          echo "example.com" >> ${{ github.workspace }}/haraka/config/host_list

          # configure smtp
          mv ${{ github.workspace }}/haraka/config/smtp.ini ${{ github.workspace }}/haraka/config/smtp.ini.orig
          cat <<SMTP > ${{ github.workspace }}/haraka/config/smtp.ini
          listen=127.1.2.3:2525
          [headers]
          max_lines=1000
          max_received=100
          SMTP

          # configure plugins
          mv ${{ github.workspace }}/haraka/config/plugins ${{ github.workspace }}/haraka/config/plugins.orig
          cat <<PLUGINS > ${{ github.workspace }}/haraka/config/plugins
          helo.checks
          rcpt_to.in_host_list
          headers
          queue/test
          PLUGINS

          # configure systemd service
          cat <<SVC > haraka.service
          #
          # systemd service file for Haraka
          #
          # Ensure that `daemonize` in `smtp.ini` is set to `false` (which is the default value).
          #
          # Put this file in /etc/systemd/system,  modify the paths to suit, then run:
          # sudo systemctl enable haraka
          # sudo systemctl start haraka
          #

          [Unit]
          Description=Haraka MTA
          After=syslog.target network.target remote-fs.target nss-lookup.target

          [Service]
          Type=simple
          PIDFile=/var/run/haraka.pid
          ExecStart=/usr/local/bin/haraka -c ${{ github.workspace }}/haraka
          KillMode=process
          PrivateTmp=True

          [Install]
          WantedBy=multi-user.target
          
          SVC
          sudo mv haraka.service /etc/systemd/system/haraka.service

      - name: Start Haraka
        run: sudo systemctl start haraka

      - name: Install swaks
        run: |
          sudo apt-get update
          sudo apt-get install -y swaks

          #swaks --to rx@example.com --from tx@example.com --server 127.1.2.3 --port 2525 --auth-user <username> --auth-password <password> --tls

      - name: Setup tmate session
        env:
          THE_EVENT_NAME: ${{ github.event_name }}
          THE_EVENT_PATH: ${{ github.event_path }}
          THE_EVENT_BEFORE: ${{ github.event.before }}
          THE_EVENT_AFTER: ${{ github.event.after }}
        uses: mxschmitt/action-tmate@v3
