# This is a basic workflow to help you get started with Actions

name: Debug runner via SSH

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone this repository
        uses: actions/checkout@v3

      - name: Clone stuntman repository
        uses: actions/checkout@v3
        with:
          repository: jselbie/stunserver
          path: stuntman

      - name: Install stuntman build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make libboost-dev libssl-dev

      - name: Build stuntman client and server
        run: |
          cd stuntman
          make

      - name: Install stuntman client
        run: |
          mkdir -p ~/.local/bin
          install -t ~/.local/bin stuntman/stunclient

      - name: Setup tmate session
        env:
          GOPATH: ${{ github.workspace }}
        uses: mxschmitt/action-tmate@v3
